Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
    numeros.remove(4)
ValueError: list.remove(x): x not in list