try:
    print(7 / 0)
except:
    print("Ha ocurrido un error")
    raise  # vuelve a levantar una excepci√≥n ya atrapada