False
Traceback (most recent call last):
  File "c:\Users\vnico\Desktop\Resumen Python 3\codigo\20-objetos\propiedad_1.py", line 12, in <module>
    pizza.pinia_permitida = True
AttributeError: can't set attribute